#!/usr/bin/env bash
# installs the 'ufw' firewall and,

apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw enable
ufw default deny incoming
ufw default allow outgoing
sudo ufw allow ssh
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
