#!/usr/bin/env bash
# Install and configure Nginx to use port 8080 instead of port 80
apt-get install nginx -y & sudo service nginx start
sed -i 's/80/8080/g' /etc/nginx/nginx.conf
sudo service nginx stop
