#!/usr/bin/env bash
# Install and configure Nginx to use port 8080 instead of port 80
sed -i 's/80/8080/g' /etc/nginx/nginx.conf
sudo bash -c "(service nginx start | service nginx stop)"
sudo service nginx stop
