#!/usr/bin/env bash
# Update the package manager
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Create a backup of the default Nginx configuration
sudo mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Create a new default configuration file
sudo touch /etc/nginx/sites-available/default
sudo chmod 666 /etc/nginx/sites-available/default

# Add the Nginx configuration
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html;
        server_name _;
        location / {
                echo \"Holberton School\";
                return 200;
        }
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
